### ISSUE TITLE
Micro-optimization

### ISSUE THREAD

**Issue by alessioalex** [Threadster/express-joi-validator#2]
Could I suggestion replacing https://github.com/Threadster/express-joi-validator/blob/master/index.js#L15-L25 with:

     ['params', 'body', 'query'].forEach(function(key) {
       if (schema[key]) { toValidate[key] = req[key]; }
     });

Sorry, couldn't help myself :dancers:

**Comment by imjoshholloway** [comment]
Thanks @alessioalex makes it cleaner
